services:

  trajectory-optimization:
    image: ghcr.io/openads-project/trajectory_optimization:v1.4.0
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: trajectory_optimization
      # --- inputs ----
      EGO_DATA_TOPIC: ~/ego_data
      OBJECT_LIST_TOPIC: ~/object_list
      REFERENCE_TRAJECTORY_TOPIC: ~/reference_trajectory
      ROUTE_TOPIC: ~/route
      # --- outputs ---
      TRAJECTORY_TOPIC: ~/trajectory
      BOUNDARY_MARKER_TOPIC: ~/visualization/boundaries
      EGO_MARKER_TOPIC: ~/visualization/ego
      OBJECT_MARKER_TOPIC: ~/visualization/objects
      # --- other -----
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      PARAMS: ${PARAMS:-/docker-ros/ws/install/trajectory_optimization/share/trajectory_optimization/config/params.yml}
      ROS_TRACING: ${ROS_TRACING:-false}
      DRIVING_MODE: ${DRIVING_MODE:-ackermann}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch trajectory_optimization trajectory_optimization.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          params:=$${PARAMS} \
          ros_tracing:=$${ROS_TRACING} \
          driving_mode:=$${DRIVING_MODE} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          object_list_topic:=$${OBJECT_LIST_TOPIC} \
          reference_trajectory_topic:=$${REFERENCE_TRAJECTORY_TOPIC} \
          route_topic:=$${ROUTE_TOPIC} \
          trajectory_topic:=$${TRAJECTORY_TOPIC} \
          boundary_marker_topic:=$${BOUNDARY_MARKER_TOPIC} \
          ego_marker_topic:=$${EGO_MARKER_TOPIC} \
          object_marker_topic:=$${OBJECT_MARKER_TOPIC}
    # volumes:
    #   - ./params.yml:/docker-ros/ws/install/trajectory_optimization/share/trajectory_optimization/config/params.yml
