include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  TARGET: dev,run
  PLATFORM: amd64
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  SLIM_BUILD_ARGS: >
    --sensor-ipc-mode=proxy
    --continue-after=30
    --show-clogs
    --http-probe=false
    --include-path /opt/ros
    --include-path /docker-ros/ws/install
    --include-path /entrypoint.sh
    --include-path /opt/acados/lib
    --include-path /bin/bash
    --include-path /usr/sbin/gosu
    --include-path /usr/sbin/groupadd
    --include-path /usr/sbin/useradd
    --include-path /usr/bin/getent
    --include-path /usr/bin/openssl
    --include-path /usr/bin/cut
    --include-path /usr/bin/touch
    --include-path /usr/bin/cp
    --include-path /usr/bin/ln
    --include-path /usr/bin/chown
    --include-path /etc/nsswitch.conf
    --include-path /etc/passwd
    --include-path /etc/group
    --include-path /etc/shadow
    --include-path /etc/gshadow
    --include-path /etc/login.defs
    --include-path /etc/default/useradd
    --include-path /root/.bashrc
    --include-path /etc/ld.so.conf
    --include-path /etc/ld.so.conf.d
    --include-path /etc/ld.so.cache
    --include-path /lib64/ld-linux-x86-64.so.2
    --include-path /lib/x86_64-linux-gnu/libc.so.6
    --include-path /lib/x86_64-linux-gnu/libm.so.6
    --include-path /lib/x86_64-linux-gnu/libgcc_s.so.1
    --include-path /lib/x86_64-linux-gnu/libstdc++.so.6
    --include-path /lib/x86_64-linux-gnu/libconsole_bridge.so.1.0
    --include-path /lib/x86_64-linux-gnu/libfmt.so.9
    --include-path /lib/x86_64-linux-gnu/liborocos-kdl.so.1.5
    --include-path /lib/x86_64-linux-gnu/libspdlog.so.1.12
    --include-path /lib/x86_64-linux-gnu/libyaml-0.so.2
  COMMAND: ros2 launch trajectory_optimization trajectory_optimization.launch.py
