include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  TARGET: dev,run
  PLATFORM: amd64
  ENABLE_RECURSIVE_VCS_IMPORT: 'false'
  COMMAND: ros2 launch trajectory_optimization trajectory_optimization.launch.py