/**:
  ros__parameters:

    # general params
    publish_frequency: 1.0
    message_frame_id: map

    # ego data params
    ego_state_model: ackermann
    ego_vel_lon: 5.0
    ego_acc_lon: 0.0
    ego_steering_angle_ack: 0.0
    ego_steering_angle_front: 0.0
    ego_steering_angle_rear: 0.0
    ego_translation_to_geometric_center: [1.4895, 0.0, 0.420]

    # reference trajectory params
    reference_n_states: 51
    reference_trajectory_horizon: 5.0
    reference_standstill: false
    reference_x0: 0.0
    reference_y0: 0.0
    reference_v0: 5.0
    reference_a: 0.0
    reference_theta0: -10.0
    reference_omega: 10.0

    # object params
    object_count: 3
    object_delta_x: 10.0
    object_delta_y: 5.0
    object_length: 4.0
    object_width: 2.0
    object_yaw: 0.0
