name: docker-ros

on:
  push:
    branches:
      - main
      - zenoh-base-image
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: gitlab.ika.rwth-aachen.de:5050
          username: ${{ github.actor }}
          password: ${{ secrets.GITLAB_TOKEN }}
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          target: dev,run
          base-image: gitlab.ika.rwth-aachen.de:5050/fb-fi/ops/docker-ros-ml-images/ros2:rmw-zenoh_jazzy-ros-base-zenoh_ci-amd64
          command: ros2 launch trajectory_optimization trajectory_optimization.launch.py
          enable-industrial-ci: true
        env:
          TARGET_CMAKE_ARGS: -DCMAKE_EXPORT_COMPILE_COMMANDS=1
