name: industrial_ci

on:
  push:
  workflow_dispatch:

jobs:
  industrial_ci:
    uses: oads-org/openads-dev-environment/.github/workflows/industrial_ci.yml@improvement/industrial-ci # TODO: switch back to main
    secrets: inherit
